### ISSUE TITLE
Webapp TODO List

### ISSUE THREAD

**Issue by whyjay17** [rightpeter/CS565_Project#9]
**4/20 (Sat)**

- [x] Integrate plugin ignore update

- [x] Fix authentication issue on refresh

**4/21 (Sun)**

- [x] Add/Implement help-page

- [x] Build user workflow (register - config - schedule setting - turn on the plugin)

- [x] Polish webstie (logo, color, about page, etc.)

**Finish by 4/22 (Mon) at the latest**
